# Generated by Django 5.0.7 on 2024-07-28 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(default=0)),
                ('pdfDirectory', models.CharField(max_length=1000)),
                ('checkAllNextAt', models.DateTimeField(default=datetime.datetime(2024, 7, 28, 16, 53, 56, 554788))),
                ('recheckIntervalDays', models.IntegerField(default=0)),
                ('recheckIntervalHours', models.IntegerField(default=0)),
                ('recheckIntervalMins', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('statusCode', models.IntegerField()),
                ('reason', models.CharField(max_length=40)),
                ('dismiss', models.BooleanField()),
                ('ignore', models.BooleanField()),
                ('pdfSource', models.CharField(max_length=1000)),
                ('finalurl', models.URLField(max_length=1000)),
                ('urlText', models.CharField(max_length=1000)),
                ('lastChecked', models.DateTimeField()),
                ('lastIteration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Links_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('finalUrl', models.URLField(max_length=1000)),
                ('moreInPdf', models.BooleanField(default=False)),
                ('urlText', models.CharField(max_length=1000)),
                ('statusCode', models.IntegerField()),
                ('reason', models.CharField(max_length=40)),
                ('pdfSource', models.CharField(max_length=1000)),
                ('broken', models.BooleanField(default=False)),
                ('dismiss', models.BooleanField(default=False)),
                ('ignore', models.BooleanField(default=False)),
                ('brokenSince', models.DateTimeField(default=datetime.datetime(2024, 7, 28, 16, 53, 56, 554200))),
                ('lastChecked', models.DateTimeField()),
                ('lastIteration', models.IntegerField(default=0)),
                ('lastLog', models.CharField(max_length=1000)),
            ],
        ),
    ]
