# Generated by Django 5.0.3 on 2024-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LinkChecker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="lastChecked",
            field=models.DateField(),
        ),
    ]
