# Generated by Django 5.0.7 on 2024-07-28 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkChecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globals',
            name='checkAllNextAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 10, 11, 48, 206497)),
        ),
        migrations.AlterField(
            model_name='links_table',
            name='brokenSince',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 10, 11, 48, 206079)),
        ),
    ]
