# Generated by Django 5.0.7 on 2024-07-29 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkChecker', '0002_alter_globals_checkallnextat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globals',
            name='checkAllNextAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 19, 3, 43, 721754)),
        ),
        migrations.AlterField(
            model_name='links_table',
            name='brokenSince',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 19, 3, 43, 721032)),
        ),
    ]
