# Generated by Django 5.0.7 on 2024-07-29 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkChecker', '0005_alter_links_table_brokensince'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links_table',
            name='brokenSince',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 19, 25, 18, 148889, tzinfo=datetime.timezone.utc)),
        ),
    ]
