# Generated by Django 5.0.7 on 2024-07-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkChecker', '0007_alter_links_table_brokensince'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links_table',
            name='brokenSince',
            field=models.DateTimeField(),
        ),
    ]
